general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: true

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "false"

gaps:
  # Gap between adjacent windows.
  inner_gap: "10px"

  # Gap between windows and the screen edge.
  outer_gap: "10px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#C4006B"


  inactive:
    enabled: false
  color: *overlay0

bar:
  height: "24px"
  position: "top"
  opacity: 1.0
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "JetBrainsMono Nerd Font"
  font_size: "12px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "window title"
      foreground: *text

  components_center:
    - type: "workspaces"
      focused_workspace_background: transparent
      focused_workspace_foreground: *text
      focused_workspace_border_color: transparent

      displayed_workspace_background: transparent
      displayed_workspace_foreground: *text
      displayed_workspace_border_color: transparent

      default_workspace_background: transparent
      default_workspace_foreground: *overlay0
      default_workspace_border_color: transparent

  components_right:

    - type: "music"
      label_not_playing: ""
      label_playing: "ÔÄÅ {song_title} - {artist_name}"
      label_paused: "ÔÅå {song_title} - {artist_name}"
      max_title_length: 20
      max_artist_length: 20
      background: transparent
      foreground: *text
      margin: 0 8

    - type: "tiling direction"
      label_horizontal: "<attr ff='Segoe Fluent Icons' fg='#a6e3a1'>ÓùÜ</attr>"
      label_vertical: "<attr ff='Segoe Fluent Icons' fg='#a6e3a1'>ÓùÖ</attr>"
      background: transparent
      foreground: *text
      margin: 0 8 

    - type: "battery"
      foreground: *text
      margin: 0 8
      label_draining   : "<attr ff='Segoe Fluent Icons' fg='#fab387'>ÓÆ• </attr>{battery_level}%"
      label_power_saver: "<attr ff='Segoe Fluent Icons' fg='#fab387'>ÓÆª </attr>{battery_level}%"
      label_charging   : "<attr ff='Segoe Fluent Icons' fg='#fab387'>ÓÆ∞ </attr>{battery_level}%"

    - type: "network"
      foreground: *text
      margin: 0 8
      label_no_internet: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ôúù </attr>Dsc"
      label_ethernet: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó†π </attr>Eth"
      label_wifi_strength0: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó°≤ </attr>0%"
      label_wifi_strength25: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó°≥ </attr>25%"
      label_wifi_strength50: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó∞æ </attr>50%"
      label_wifi_strength75: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó∞ø </attr>75%"
      label_wifi_strength100: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó∞ø </attr>100%"
      border_color: *peach

    - type: "volume"
      foreground: *text
      margin: 0 8
      label       : "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó¶í </attr>{volume_level}%"
      label_low   : "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó¶ì </attr>{volume_level}%"
      label_medium: "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó¶î </attr>{volume_level}%"
      label_high  : "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó¶ï </attr>{volume_level}%"
      label_mute  : "<attr ff='Segoe Fluent Icons' fg='#fab387'>Ó™Ö </attr>{volume_level}%"

    - type: "clock"
      foreground: *text
      padding: 0 8
      label: "<attr ff='Segoe Fluent Icons' fg='#89b4fa'>Óûá </attr>{formatted_time}"
      time_formatting: "MMM dd"

    - type: "clock"
      foreground: *text
      padding: 0 8
      label: "<attr ff='Segoe Fluent Icons' fg='#89b4fa'>ÓÑ° </attr>{formatted_time}"
      time_formatting: "HH:mm"

workspaces:
  - name: "1"
    display_name: "main"
    bind_to_monitor: 1
    keep_alive: true
  - name: "2"
    bind_to_monitor: 1
  - name: "3"
    bind_to_monitor: 1
  - name: "4"
    bind_to_monitor: 2
  - name: "5"
    bind_to_monitor: 2
  - name: "6"
    bind_to_monitor: 2
  - name: "7"
    display_name: "chat"
    bind_to_monitor: 2
  - name: "8"
    display_name: "mail"
    bind_to_monitor: 2
  - name: "9"
    display_name: "üé∂"
    bind_to_monitor: 2

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless runnin:g
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/ScreenClippingHost|carlo/"

  - command: "set floating"
    match_class_name: "#32770"

  - command: "set floating"
    match_process_name: "/BuildProtokoll"

  - command: "set floating"
    match_title: "/Rename|Run/Debug Configurations|Settings|Harpoon/"

  - command: "set tiling"
    match_title: "Settings"

  - command: "move to workspace 1"
    match_process_name: "JetBrains Rider"

  - command: "move to workspace 7"
    match_process_name: "/ms-teams|Discord/"

  - command: "move to workspace 8"
    match_process_name: "OUTLOOK"

  - command: "move to workspace 9"
    match_process_name: "Spotify"

  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+C"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+C"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec %SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -nologo"
    binding: "Alt+Shift+Enter"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]

#################################################################################################

# Palette
rosewater: &rosewater '#f5e0dc'
flamingo : &flamingo '#f2cdcd'
pink     : &pink '#f5c2e7'
mauve    : &mauve '#cba6f7'
red      : &red '#f38ba8'
maroon   : &maroon '#eba0ac'
peach    : &peach '#fab387'
yellow   : &yellow '#f9e2af'
green    : &green '#a6e3a1'
teal     : &teal '#94e2d5'
sky      : &sky '#89dceb'
sapphire : &sapphire '#74c7ec'
blue     : &blue '#89b4fa'
lavender : &lavender '#b4befe'
text     : &text '#cdd6f4'
subtext1 : &subtext1 '#bac2de'
subtext0 : &subtext0 '#a6adc8'
overlay2 : &overlay2 '#9399b2'
overlay1 : &overlay1 '#7f849c'
overlay0 : &overlay0 '#6c7086'
surface2 : &surface2 '#585b70'
surface1 : &surface1 '#45475a'
surface0 : &surface0 '#313244'
base     : &base '#1e1e2e'
mantle   : &mantle '#181825'
crust    : &crust '#11111b'
